const $=id=>document.getElementById(id);let processing=false;let playing=false;let audioTimer=null;let promptIndex=0;
const prompts=['“后来雨停了吗？”','“你还记得散场后去了哪里吗？”','“那时候，爷爷是什么样子？”'];
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function switchView(view){document.querySelectorAll('[data-view-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.viewPanel===view));document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(control=>control.addEventListener('click',()=>switchView(control.dataset.view)));

function finishReceive(){const sheet=$('processingSheet');$('processBar').style.width='100%';$('processEyebrow').textContent='已经认出一点线索';$('processTitle').textContent='这段声音，和一段旧故事相认了';$('processHint').textContent='旧电影院 · 爷爷 · 一场雨';setTimeout(()=>{sheet.hidden=true;processing=false;$('arrivalCard').classList.add('received');$('receiveButton').innerHTML='<span>原声已经收好</span><b>仅自己可见</b>';const card=$('unfoldCard');card.classList.remove('locked');card.classList.add('revealed');card.scrollIntoView({behavior:'smooth',block:'center'});toast('一段旧故事慢慢浮现了')},950)}
function receiveVoice(){if(processing)return;if($('arrivalCard').classList.contains('received')){$('unfoldCard').scrollIntoView({behavior:'smooth',block:'center'});return}processing=true;const sheet=$('processingSheet');sheet.hidden=false;$('processBar').style.width='14%';$('processEyebrow').textContent='正在接住原声';$('processTitle').textContent='让这段声音慢慢浮现';$('processHint').textContent='原声始终保留';setTimeout(()=>{$('processBar').style.width='48%';$('processEyebrow').textContent='听见了一个地方';$('processTitle').textContent='旧电影院附近';$('processHint').textContent='地点来自珠珠同步时的线索'},800);setTimeout(()=>{$('processBar').style.width='76%';$('processEyebrow').textContent='听见了熟悉的人';$('processTitle').textContent='她提到了爷爷';$('processHint').textContent='正在寻找相似的旧片段'},1650);setTimeout(finishReceive,2500)}
$('receiveButton').addEventListener('click',receiveVoice);$('hardwareDemo').addEventListener('click',()=>{const card=$('arrivalCard');card.classList.remove('hardware-pop');void card.offsetWidth;card.classList.add('hardware-pop');toast('珠珠轻震一下：原声已保存，等回到手机')});

$('playEvidence').addEventListener('click',()=>{const range=$('audioProgress');const button=$('playEvidence');if(playing){playing=false;clearInterval(audioTimer);button.textContent='继续播放';return}playing=true;button.textContent='暂停';audioTimer=setInterval(()=>{range.value=Number(range.value)+1;$('audioTime').textContent=`00:${String(range.value).padStart(2,'0')}`;if(Number(range.value)>=18){clearInterval(audioTimer);playing=false;button.textContent='再听一次';range.value=0}},250)});
$('audioProgress').addEventListener('input',event=>$('audioTime').textContent=`00:${String(event.target.value).padStart(2,'0')}`);
$('traceToggle').addEventListener('click',()=>{const panel=$('tracePanel');panel.hidden=!panel.hidden;$('traceToggle').textContent=panel.hidden?'看看这段故事从哪里来':'收起来源'});
$('nextPrompt').addEventListener('click',()=>{promptIndex=(promptIndex+1)%prompts.length;const card=$('promptCard');card.style.animation='none';void card.offsetWidth;card.style.animation='promptIn .6s ease';$('promptText').textContent=prompts[promptIndex]});
$('usePrompt').addEventListener('click',()=>toast('这句话已放大显示，交给家人轻声问'));
document.querySelectorAll('.place-pin').forEach(pin=>pin.addEventListener('click',()=>{document.querySelectorAll('.place-pin').forEach(item=>item.classList.remove('active'));pin.classList.add('active');const garden=pin.dataset.place==='garden';$('placeStory').innerHTML=garden?'<small>老院子 · 3 段声音</small><h3>院子里那棵枇杷树</h3><p>“每年春天，树下总落着一层白花……”</p><button data-view="story">回到这段声音</button>':'<small>旧电影院 · 2 段声音</small><h3>第一次和爷爷看电影</h3><p>“电影院门口有一棵很大的香樟树……”</p><button data-view="story">回到这段声音</button>';const next=$('placeStory').querySelector('[data-view]');next.addEventListener('click',()=>switchView('story'))}));
$('locationToggle').addEventListener('click',event=>{const value=event.currentTarget.querySelector('em');value.textContent=value.textContent==='开启'?'关闭':'开启';toast(value.textContent==='开启'?'经过熟悉地点时会偶尔提醒':'地点提醒已关闭')});
